### ISSUE TITLE
Error when installing with Icarus Mod Manager 1.4

### ISSUE THREAD

**Issue by TheOringalIntreeg** [zailfyer/Icarus_Mods#1]

**Comment by TheOringalIntreeg** [comment]
My bad. It was layer 8 of the OSI model. User error.

**Comment by TheOringalIntreeg** [comment]
Never mind. That previous comment was a false negative.
When I select the level 100 pak in the Icarus Mod Manager 1.4 after extracting, I get an error. 
"Access violation at address 006805EC in module 'IcarusModManager.exe' Read of address 00000000."

**Comment by TheOringalIntreeg** [comment]
Found the fix. Deleted Icarus Mod Manager 1.4 and installed Icarus Mod Manager 1.6.7. Mod installs now.

**Comment by zailfyer** [comment]
Sorry for the late reply here im glad you were able to reesalve your issue here.  i do want to note there might be some other issues as i havent updated it in a wile.  there has been some game updates that changed the level curve and max that i havent had time to update and acount for.
